apiVersion: v1
kind: Service
metadata:
  name: autodeploy99
  namespace: namespace-workflow-1701222656639
spec:
  type: LoadBalancer
  selector:
    app: autodeploy99
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000